---
title: "Metamorphosis"
author: "Katie McFarland"
date: "4/24/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# SET WORKING DIRECTORY 
# knitr::opts_knit$set(root.dir = "C:/Users/katherine.mcfarland/Documents/GitHub/EAD-ASEB-Airradians_Larvae_crossgen_OA/RAnalysis/Data")
# knitr::opts_knit$set(root.dir = "C:/Users/samgj/Documents/Github_repositories/EAD-ASEB-Airradians_F3_Larvae_OA/RAnalysis") # Sam's
knitr::opts_knit$set(root.dir = "C:/Users/samuel.gurr/Documents/Github_repositories/EAD-ASEB-Airradians_F3_Larvae_OA/RAnalysis") # Sam's

```


```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(emmeans)
library(rcompanion)
library(FSA)
```


### Load Data
```{r}
#Here we are assing our data fram the name "df" so that we do not have to type out the full file name everytime we want to call it.
df<-read.csv("DAta/Physiology/metamorphosis.csv", header = T)

#df$Percent.deformed=as.numeric(df$Percent.deformed)

df$Parent=as.factor(df$Parent)
df$Ttreatment=as.factor(df$Treatment)
df$Exposure.OA=as.factor(df$Exposure.OA)
df$Rep=as.factor(df$Rep)

df$Generation=as.factor(df$Generation)

df$Treatment <- factor(df$Treatment,levels = c("Low OA", "Moderate OA", "High OA"))

df$Exposure.OA <- factor(df$Exposure.OA,levels = c("LOW", "MODERATE", "HIGH"))

df$Parent <- factor(df$Parent,levels = c("LOW", "MODERATE", "HIGH"))

#to look at columns names of your data frame
head(df)

#Sturcture of the data - to check that variables are properly assigned to facotr or variable
str(df)
```

# Calculations
```{r}
df$precent.metamorphose <- (df$live_spat)/(df$live_spat+df$live_larvae)
```


```{r}

df_F2_21 <- df%>%
  filter(Age=="21")


df_F3_19 <- df%>%
  filter(Age=="19")
```

# Percent Successful Metamorphosis = live_spat / (live spat + dead spat)
```{r}
ggplot(data=df_F2_21, aes(x=Exposure.OA, y=sucessful.metamorphosis, fill=Exposure.OA)) +
  geom_boxplot()+  scale_fill_manual(values=c("forestgreen","orange", "purple"))+
  theme_bw() +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(title="Percent Successful metamorphosis (2023: F2 Larvae - Age 21 days) ", x ="Treatment", y = "Percent sucessful metamorphosis")



# MEan SE
Perc_Met_MeanSE <- ggplot(df_F2_21,
                       aes(x=Exposure.OA, 
                                         y=sucessful.metamorphosis,
                                         fill=factor(Exposure.OA)), 
                                  stat="identity") +
                       geom_point(aes(colour = Exposure.OA), 
                                        position = position_dodge2(width = 0.2), size =2) + 
                       stat_summary(fun.y="mean", size = 0.5,
                                          position = position_dodge2(width = 1)) +
                       stat_summary(fun.min = function(x) mean(x) - sd(x)/sqrt(length(x)), 
                                          fun.max = function(x) mean(x) + sd(x)/sqrt(length(x)),
                                          geom = 'errorbar', width = 0.1, size = 0.5,
                                          position = position_dodge2(width = 0.2),
                                    color=c("forestgreen","orange")) + 
                        labs(title="Percent Successful metamorphosis (2023: F2 Larvae - Age 21 days)", 
                            x ="Treatment", 
                            y = "Percent sucessful metamorphosis") +
                        # scale_fill_manual(breaks=c("Low pCO2", "Moderate pCO2", "High pCO2"), 
                        #                    values=c("forestgreen","orange", "purple")) +
                        scale_color_manual(breaks=c("Low pCO2", "Moderate pCO2"), 
                                           values=c("forestgreen","orange")) +
                        scale_x_discrete(labels=c("L", "M")) +
                        scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
                        theme_classic() +
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(), 
                              axis.title.x=element_blank(),
                              axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1),
                              axis.text=element_text(size=8),
                              plot.title = element_text(size=12),
                              legend.position="none") 
print(Perc_Met_MeanSE)


Perc_Mort_MeanSE <- ggplot(df_F2_21,
                       aes(x=Exposure.OA, 
                                         y=1-(sucessful.metamorphosis),
                                         fill=factor(Exposure.OA)), 
                                  stat="identity") +
                       geom_point(aes(colour = Exposure.OA), 
                                        position = position_dodge2(width = 0.2), size =2) + 
                       stat_summary(fun.y="mean", size = 0.5,
                                          position = position_dodge2(width = 1)) +
                       stat_summary(fun.min = function(x) mean(x) - sd(x)/sqrt(length(x)), 
                                          fun.max = function(x) mean(x) + sd(x)/sqrt(length(x)),
                                          geom = 'errorbar', width = 0.1, size = 0.5,
                                          position = position_dodge2(width = 0.2),
                                    color=c("forestgreen","orange")) + 
                        labs(title="Post-metamorphic mortality (2023: F2 Larvae - Age 21 days)", 
                            x ="Treatment", 
                            y = "Percent mortality") +
                        # scale_fill_manual(breaks=c("Low pCO2", "Moderate pCO2", "High pCO2"), 
                        #                    values=c("forestgreen","orange", "purple")) +
                        scale_color_manual(breaks=c("Low pCO2", "Moderate pCO2"), 
                                           values=c("forestgreen","orange")) +
                        scale_x_discrete(labels=c("L", "M")) +
                        scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
                        theme_classic() +
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(), 
                              axis.title.x=element_blank(),
                              axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1),
                              axis.text=element_text(size=8),
                              plot.title = element_text(size=12),
                              legend.position="none") 
```

## precent.metamorphose = (live sapt / (live spat + live larvae)) 
```{r}
ggplot(data=df_F2_21, aes(x=Exposure.OA, y=precent.metamorphose, fill=Exposure.OA)) +
  geom_boxplot()+  scale_fill_manual(values=c("forestgreen","orange", "purple"))+
  theme_bw() +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(title="Percent Metamorphosed (2023: F2 Larvae - Age 21 days) ", x ="Treatment", y = "Percent metamorphosed")
```

# Percent Successful Metamorphosis = live_spat / (live spat + dead spat)
```{r}
ggplot(data=df_F3_19, aes(x=Exposure.OA, y=sucessful.metamorphosis, fill=Exposure.OA)) +
  geom_boxplot()+  scale_fill_manual(values=c("forestgreen","orange", "purple"))+
  theme_bw() +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(title="Percent Successful metamorphosis, grouped by parentage (2023: F3 Larvae - Age 19 days) ", x ="Treatment", y = "Percent sucessful metamorphosis")+
  facet_wrap("Parent")
```

## precent.metamorphose = (live sapt / (live spat + live larvae)) 

```{r}

ggplot(data=df_F3_19, aes(x=Exposure.OA, y=metamorphesed, fill=Exposure.OA)) +
  geom_boxplot()+  scale_fill_manual(values=c("forestgreen","orange", "purple"))+
  theme_bw() +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(title="Percent metamorphesed, grouped by parentage (2023: F3 Larvae - Age 19 days) ", x ="Treatment", y = "Percent metamorphosed")+
  facet_wrap("Parent")
```
# Looking at just high and low parentage
```{r}

df_F3_19_trim <- df_F3_19%>%
   filter(Parent %in% c("HIGH", "LOW"))
  #filter(Parent=="HIGH, LOW")

ggplot(data=df_F3_19_trim, aes(x=Exposure.OA, y=metamorphesed, fill=Exposure.OA)) +
  geom_boxplot()+  scale_fill_manual(values=c("forestgreen","orange", "purple"))+
  theme_bw() +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(title="Percent metamorphesed, grouped by parentage (2023: F3 Larvae - Age 19 days) ", x ="Treatment", y = "Percent sucessful metamorphosis")+
  facet_wrap("Parent")
```

```{r}
df$sucessful.metamorphosis_trans <- asin(sqrt(df$sucessful.metamorphosis))

df_F2_21 <- df%>%
  filter(Age=="21")

df_F3_19 <- df%>%
  filter(Age=="19")
```

# ANOVA for F2 day 21
NO significant affect (p = 0.0694)
```{r}
aovMOD_F2_21 <- lm(sucessful.metamorphosis ~ Exposure.OA, data=df_F2_21)
shapiro.test(resid(aovMOD_F2_21)) # 0.2758 -  norm
leveneTest(aovMOD_F2_21) # 0.2909- pass

summary(aov(aovMOD_F2_21))
aovMOD_F2_21_posthoc <- emmeans(aovMOD_F2_21, pairwise~Exposure.OA, adjust="tukey")
multcomp::cld(aovMOD_F2_21_posthoc$emmeans,alpha = 0.5, Letters = letters)

#aovMOD_F2_21 <- lm(sucessful.metamorphosis_trans ~ Parent * Exposure.OA, data=df_F2_21)
#shapiro.test(resid(aovMOD_F2_21)) # 0.05757 -  norm
#leveneTest(aovMOD_F2_21) # 0.364- pass


```

# ANOVA for F3 day 19
```{r}
aovMOD_F3_19 <- lm(sucessful.metamorphosis ~ Parent * Exposure.OA, data=df_F3_19, random = ~Rep)
shapiro.test(resid(aovMOD_F3_19)) # 0.001961 -  not norm
leveneTest(aovMOD_F3_19) # 0.5261- pass

srh_F3_19 <- scheirerRayHare(sucessful.metamorphosis ~ Parent * Exposure.OA, data=df_F3_19)
#                    Df Sum Sq      H p.value
# Parent              2 197.56 3.1726 0.20468
# Exposure.OA         2  30.72 0.4934 0.78138
# Parent:Exposure.OA  4 525.22 8.4347 0.07689
# Residuals          18 865.50

df$sucessful.metamorphosis_trans <- asin(sqrt(df$sucessful.metamorphosis))

aovMOD_F3_19 <- lm(sucessful.metamorphosis_trans ~ Parent * Exposure.OA, data=df_F3_19)
shapiro.test(resid(aovMOD_F3_19)) # 0.05757 -  norm
leveneTest(aovMOD_F3_19) # 0.364- pass
summary(aovMOD_F3_19)
#                                    Estimate Std. Error t value Pr(>|t|)    
# (Intercept)                         1.30560    0.13661   9.557 1.78e-08 ***
# ParentMODERATE                      0.11257    0.19319   0.583   0.5673    
# ParentHIGH                         -0.49692    0.19319  -2.572   0.0192 *  
# Exposure.OAMODERATE                 0.07211    0.19319   0.373   0.7133    
# Exposure.OAHIGH                     0.14914    0.19319   0.772   0.4501    
# ParentMODERATE:Exposure.OAMODERATE -0.27065    0.27322  -0.991   0.3350    
# ParentHIGH:Exposure.OAMODERATE      0.46421    0.27322   1.699   0.1065    
# ParentMODERATE:Exposure.OAHIGH     -0.29927    0.27322  -1.095   0.2878    
# ParentHIGH:Exposure.OAHIGH          0.13942    0.27322   0.510   0.6160


summary(aov(aovMOD_F3_19))
aovMOD_F3_19_posthoc <- emmeans(aovMOD_F3_19, pairwise~Parent, adjust="tukey")
multcomp::cld(aovMOD_F3_19_posthoc$emmeans,alpha = 0.5, Letters = letters)
```









```{r}
kruskal.test(sucessful.metamorphosis ~ Exposure.OA, data = df_F2_21)
```

```{r}
scheirerRayHare(sucessful.metamorphosis ~ Exposure.OA*Parent,
                data = df_F3_19)

dunnTest(sucessful.metamorphosis ~ Exposure.OA,
                data = df_F3_19,
              method="bh")

dunnTest(sucessful.metamorphosis ~ Parent,
                data = df_F3_19,
              method="bh")
```

